#git aliases

alias g='git'
alias gs='git status'
alias gi='git init'
alias ga='git add'
alias ga.='git add .'
alias gc='git commit -m'
alias gca='git commit -a -m'
alias gpl='git pull'
alias gp='git push'
alias gf='git fetch'
alias gm='git merge'
alias gb='git branch'
alias gl='git log'
alias gd='git diff'
alias gch='git checkout'
