#!/bin/sh

# this changes the permissions of all directories and files to drwxr-xr-x and -rw-r--r-- recursivly in the given directory
# usefull if you copied data from an FAT formated drive.
# be CAREFUL with usage not to change already properly set permissions

find $1  \( -type d -exec chmod 0755 -- {} + \) -o \( -type f -exec chmod 0644 -- {} + \)
