#!/bin/bash

# adds relative $percent to the brightness

percent=20

cur=$(xbacklight)
inc=$(bc <<< $cur*$percent/100)
if [ ${inc%.*} -le 1 ]
then
	inc=1
fi

case "$1" in
    inc)
        ;;
    dec)
            inc=-$inc
	;;
    *)
        echo "Usage: $0 {inc|dec}"
        exit 2
esac

if [[ $1 == "dec" && ${cur%.*} -lt 1 ]]
then
	exit
fi
xbacklight -inc $inc
