#!/bin/sh

# This script is specified in the sudoers so that it can be run without typing the password but having root privileges
# Make sure only correct user can edit this file such that no vulnerable commands can be executed here

# This starts or stops openvpn to connect or disconnect for the VPN stusta
# exit code:	0	no state change
#		1	state changed (from not connected to connected or reversed)
# 		-1	error occured

connect=connect
disconnect=disconnect
vpn_info=/home/leo/scripts/i3/vpn_info
config=/home/leo/.config/vpn/stusta

case "$1" in
	$connect)
		echo stusta connect
		echo test connection..
		$vpn_info stusta
		if [ $? -eq 0 ]
	       	then # already connected
			echo already connected
			exit 0
		fi
		echo begin connect
		openvpn --daemon --config $config
		exit 1
		;;
	$disconnect)
		echo stusta disconnect
		$vpn_info stusta
		if [ $? -eq 1 ]
	       	then # already connected
			echo already disconnected
			exit 0
		fi
		# stop vpn
		killall openvpn
		exit 1
		;;
	*)
		;;
esac

