#!/bin/sh
# handle vpn connections

# exit code:	0 	all fine, (stusta: no state change
# 		2 	wrong usage
# 		-1	some error

tum=tum
stusta=stusta
connect=connect
disconnect=disconnect
usage="Usage: $0 {$connect|$disconnect} {$tum|$stusta}"
config_path=/home/leo/.config/vpn
vpn_stusta=/home/leo/scripts/i3/vpn_stusta

case "$2" in
    $tum)
	case "$1" in
	    $connect)
		# connect to tum
		openconnect --config $config_path/tum asa-cluster.lrz.de < $config_path/tumpwd
		;;
	    $disconnect)
		# disconnect to tum
		kill -2 $(cat $config_path/tumpid)
		;;
	    *)
        	echo $usage
	        exit 2
		;;
	esac
        ;;
    $stusta)
	case "$1" in
	    $connect)
		$vpn_stusta connect
		exit $?
		;;
	    $disconnect)
		$vpn_stusta disconnect
		exit $?
		;;
	    *)
        	echo $usage
	        exit 2
		;;
	esac
        ;;
    *)
        echo $usage
        exit 2
esac

exit 0
