#!/bin/bash

SCRIPTS="/home/leo/scripts/"
VPN="i3/vpn"
VPNINFO="i3/vpn_info"
RUNWITHVPN="run_command_with_active_vpn"

LOCALFILE="/home/leo/Documents/Security/allPasswords.kdbx" 
REMOTEFILE="private/auto_backup/backup_pwd_$(date +%F).kdbx"

VPNACT="$SCRIPTS$VPN connect stusta"
VPNDEACT="$SCRIPTS$VPN disconnect stusta"
VPNCHECK="$SCRIPTS$VPNINFO stusta"
COMMAND="sftp -o ConnectTimeout=5 mammut" # <<< "put $LOCALFILE $REMOTEFILE" 

# this piping is kind of cheaty but works because no other command then $COMMAND reads from sdtin. Somehow two commands connected with a pipe won't work as Variable
$SCRIPTS$RUNWITHVPN "$VPNACT" "$VPNDEACT" "$VPNCHECK" "$COMMAND" <<< "put $LOCALFILE $REMOTEFILE"

