#!/bin/sh
# handle vpn connections

tum=tum
stusta=stusta
connect=connect
disconnect=disconnect
usage="Usage: $0 {$connect|$disconnect} {$tum|$stusta}"
config_path=~/.config/vpn

case "$2" in
    $tum)
	case "$1" in
	    $connect)
		# connect to tum
		ciscovpn -s < $config_path/tum
		;;
	    $disconnect)
		# disconnect to tum
		ciscovpn disconnect
		;;
	    *)
        	echo $usage
	        exit 2
		;;
	esac
        ;;
    $stusta)
	case "$1" in
	    $connect)
		# TODO connect to stusta
		exit 3
		;;
	    $disconnect)
		# TODO disconnect from stusta
		exit 3
		;;
	    *)
        	echo $usage
	        exit 2
		;;
	esac
        ;;
    *)
        echo $usage
        exit 2
esac

exit 0
